### ISSUE TITLE
File Offset missmatch (get_file_offset())

### ISSUE THREAD

**Issue by dobin** [malwarefrank/dnfile#77]
Issue: The offset returned by `get_file_offset()` is wrong by 0x1E00. 

Details: 
I try to get the file offset for all the structs printed by `dndump.py` with `struct.get_file_offset()`: 

At:
[dndump.py#L191C23-L192C1](https://github.com/malwarefrank/dnfile/blob/master/examples/dndump.py#L191C23-L192C1)

Add: 
```
                    ostream.writeln("[%d]:" % (i + 1))
                    ostream.writeln("File offset: " + str(row.struct.get_file_offset()))
```

Which gives with [dotnet-test.dll](https://github.com/dobin/avred/blob/main/tests/data/dotnet-test.dll) for example:
```
 MethodDef:
    [1]:
    File offset: 8748
      Rva:        0x2048
      Name:       .ctor
      Signature:  200001
      ParamList: (empty)
      ImplFlags:
        miIL
        miManaged
      Flags:
        mdHideBySig
        mdPublic
        mdRTSpecialName
        mdReuseSlot
        mdSpecialName
```

The file offset is `8748`, but the file is only 2023 bytes big. 

The effective offset is 8748 - 7680: 
```
$ hexdump -vC -s $((8748 - 7680)) -n 16  dotnet-test.dll
0000042c  48 20 00 00 00 00 86 18  20 02 06 00 01 00 50 20  |H ...... .....P |
```
The RVA=0x2048 is at the beginning of the MethodDef, as little endian: `48 20`. 

Note that 7680 is 0x1E00. 

Any idea where this 0x1E00 offset is coming from? Is it stable and i can just subtract this offset? Is this a bug?
Probably the RVA to Offset calculation is done not completely correctly. There also seems to be no header or section at the offset 0x1E00 in DotNet PE files.

**Comment by malwarefrank** [comment]
Thank you for the bug report.  I do not remember if I am calculating the file offsets myself or relying on the pefile package.  I should have time to dig into this issue next week.

**Comment by malwarefrank** [comment]
@dobin I think I found the problem.  Some of the struct file offsets were being calculated based off the stream rva instead of the stream file offset.  I just the fixes to a branch and created PR #80 . Check it out and let me know if it looks good to you.

This is the result now on the dotnet-test.dll file you mentioned:

```
 MethodDef:
    [1]:
    File offset: 1068
      Rva:        0x2048
      Name:       .ctor
      Signature:  200001
      ParamList: (empty)
      ImplFlags:
        miIL
        miManaged
      Flags:
        mdHideBySig
        mdPublic
        mdRTSpecialName
        mdReuseSlot
        mdSpecialName
    [2]:
    File offset: 1082
      Rva:        0x2050
      Name:       .ctor
      Signature:  20010105
      ParamList: (empty)
      ImplFlags:
```

**Comment by dobin** [comment]
Awesome! 
Nice, i assumed something like using an RVA was happening. 

But, can't test it atm - there seems to be a little mistake?
 
```
~/repos/dnfile/examples$ git pull
Already up to date
~/repos/dnfile/examples$ git status
On branch master
Your branch is up to date with 'origin/master'.

~/repos/dnfile/examples$ python3 dndump.py ../../avred/tests/data/dotnet-test.dll
Traceback (most recent call last):
  File "dndump.py", line 340, in <module>
    sys.exit(main())
  File "dndump.py", line 333, in main
    render_pe(ostream, dn)
  File "dndump.py", line 172, in render_pe
    file_offset = stream.get_file_offset()
AttributeError: 'MetaDataTables' object has no attribute 'get_file_offset'
```

Line 172 has been introduced in https://github.com/malwarefrank/dnfile/commit/d136d747fcc8e5daa61fb9265bbef0db96c230f9 and `get_file_offset()` in https://github.com/malwarefrank/dnfile/commit/d22cd7f3ed2e04938b89c285372dd988d7e0c6e4

**Comment by malwarefrank** [comment]
@dobin It is working for me on your test file.  You may have forgotten to install the updated version in your working environment, "pip install -U dnfile"

**Comment by dobin** [comment]
Oh, my mistake! I verified it with another file, looks alright to me: 

```
MethodDef:
    [1]:
      File offset: 0x2a09c
      Rva:        0x2050
```

```
$ hexdump -vC -s $((0x2a09c)) -n 16 Rubeus.exe
0002a09c  50 20 00 00 00 00 96 00  92 c4 e4 35 01 00 00 00  |P .........5....|
0002a0ac
```

0x2050 is as expected `0x50 0x20`, lgtm!
